### ISSUE TITLE
Screenshots?

### ISSUE THREAD

**Issue by PySimpleGUI** [Thiagojm/RngKitPSG#1]
Hi there.... it seems like you've got a GUI in your project, but I can't tell for sure.  It would be great to see some screenshots in your readme if you've got a moment to add them.  They definitely grab the attention of visitors as it's not all that common for Python programs to have a GUI and when they do, people like seeing pictures.

**Comment by Thiagojm** [comment]
Added SS to the readme

![image](https://user-images.githubusercontent.com/30575561/99856631-24449680-2b68-11eb-9d12-2537df1ddb6a.png)

![image](https://user-images.githubusercontent.com/30575561/99856669-3aeaed80-2b68-11eb-85e5-5df83d0e19a3.png)

![image](https://user-images.githubusercontent.com/30575561/99856685-45a58280-2b68-11eb-9a5b-a7f71be7dd32.png)

**Comment by PySimpleGUI** [comment]
VERY NICE!

I had no idea!  I only knew you used PySimpleGUI and didn't know the extent.  These are awesome to see.  I like it! There's a lot more to your GUI than I thought there would be.

**Comment by PySimpleGUI** [comment]
I'm going to be stealing your sunken text status idea.  It's a really nice touch and an easy way to draw attention to and group information.

**Comment by Thiagojm** [comment]
I am very grateful for the excellent tool that is PySimpleGUI. Keep up the good work!!

**Comment by PySimpleGUI** [comment]
Thank you... I will... seeing results like yours keeps the project going.

**Comment by PySimpleGUI** [comment]
I used your status idea in this little program that downloads youtube videos.

![image](https://user-images.githubusercontent.com/46163555/100227290-e8eef280-2eee-11eb-95d8-3b038d9135a9.png)

Very clever idea you had.

**Comment by Thiagojm** [comment]
> I used your status idea in this little program that downloads youtube videos.
> 
> ![image](https://user-images.githubusercontent.com/46163555/100227290-e8eef280-2eee-11eb-95d8-3b038d9135a9.png)
> 
> Very clever idea you had.

Very nice!! Thanks!
